#!/command/with-contenv bash

set -e

export PATH=${PATH}:/usr/sbin

require_env() {
	var_name="$1"
	if [ -z "${!var_name:-}" ]; then
		echo "ERROR: required environment variable ${var_name} is not set"
		exit 1
	fi
}

configure_identity_and_network() {
	echo "Configuring postfix hostname and networks"
	postconf -e myhostname="${MYHOSTNAME}"
	postconf -e mynetworks="${MYNETWORKS}"
	postconf mynetworks_style=all
	postconf -X mynetworks_style
	postconf -e inet_protocols=all
	postconf -e inet_interfaces=all
	postconf -e notify_classes="resource,software"
}

configure_submission_service() {
	echo "Configuring postfix submission service"
	postconf -M submission/inet="submission   inet   n   -   n   -   -   smtpd"
	postconf -P "submission/inet/syslog_name=postfix/submission"
	postconf -P "submission/inet/smtpd_tls_security_level=encrypt"
	postconf -P "submission/inet/smtpd_etrn_restrictions=reject"
	postconf -P "submission/inet/smtpd_sasl_type=dovecot"
	postconf -P "submission/inet/smtpd_sasl_path=inet:${DOVECOT_HOST}:${DOVECOT_SASL}"
	postconf -P "submission/inet/smtpd_sasl_security_options=noanonymous"
	postconf -P "submission/inet/smtpd_sasl_auth_enable=yes"
	postconf -P "submission/inet/milter_macro_daemon_name=ORIGINATING"
	postconf -P "submission/inet/smtpd_client_restrictions=permit_sasl_authenticated"
	postconf -P "submission/inet/smtpd_recipient_restrictions=reject_non_fqdn_recipient,reject_unknown_recipient_domain,permit_sasl_authenticated,reject"
	postconf -P "submission/inet/smtpd_helo_restrictions=permit_mynetworks"
}

configure_smtps_service() {
	echo "Configuring postfix smtps service"
	postconf -M smtps/inet="smtps     inet  n       -       n       -       -       smtpd"
	postconf -P "smtps/inet/syslog_name=postfix/smtps"
	postconf -P "smtps/inet/smtpd_tls_wrappermode=yes"
	postconf -P "smtps/inet/smtpd_sasl_auth_enable=yes"
	postconf -P "smtps/inet/smtpd_reject_unlisted_recipient=no"
	postconf -P "smtps/inet/smtpd_relay_restrictions=permit_sasl_authenticated,reject"
}

configure_maps_and_restrictions() {
	echo "Configuring postfix SQL maps and restrictions"
	postconf -e virtual_mailbox_domains=mysql:/etc/postfix/mysql-virtual-mailbox-domains.cf
	postconf -e virtual_mailbox_maps=mysql:/etc/postfix/mysql-virtual-mailbox-maps.cf
	postconf -e virtual_alias_maps=mysql:/etc/postfix/mysql-virtual-alias-maps.cf
	postconf -e smtpd_sender_login_maps=mysql:/etc/postfix/mysql-virtual-mailbox-senders.cf
	postconf -e smtpd_recipient_restrictions="permit_mynetworks,permit_sasl_authenticated,reject_unauth_destination,reject_invalid_hostname,reject_unauth_pipelining,reject_non_fqdn_sender,reject_unknown_sender_domain,reject_non_fqdn_recipient,reject_unknown_recipient_domain,reject_rbl_client b.barracudacentral.org,reject_rbl_client relays.ordb.org,reject_rbl_client dul.dnsbl.sorbs.net,reject_rbl_client http.dnsbl.sorbs.net,reject_rbl_client smtp.dnsbl.sorbs.net,reject_rbl_client socks.dnsbl.sorbs.net,permit"
	postconf -e smtpd_data_restrictions="reject_unauth_pipelining"
	postconf -e smtpd_helo_required=yes
	postconf -e smtpd_helo_restrictions="permit_mynetworks,reject_invalid_helo_hostname"
	postconf -e strict_rfc821_envelopes=yes
	postconf -e smtputf8_enable=no
	postconf -e proxy_interfaces="${PROXY_MAILNAME}"
}

configure_logging_milter_sasl_tls() {
	echo "Configuring postfix logging"
	postconf -e "maillog_file=/dev/stdout"

	echo "Configuring postfix milter (rspamd)"
	postconf -e milter_protocol=6
	postconf -e milter_mail_macros="i {mail_addr} {client_addr} {client_name} {auth_authen}"
	postconf -e milter_default_action=accept
	if [ "${RSPAMD_ENABLE:-false}" = "true" ]; then
		postconf -e smtpd_milters="inet:${RSPAMD_HOST}:${RSPAMD_PORT}"
	fi

	echo "Configuring postfix SASL"
	postconf -e virtual_transport="lmtp:${DOVECOT_HOST}:${DOVECOT_LMTP}"
	postconf -e smtpd_sasl_path="inet:${DOVECOT_HOST}:${DOVECOT_SASL}"
	postconf -e smtpd_sasl_type=dovecot
	postconf -e smtpd_sasl_auth_enable=yes
	postconf -e smtp_sasl_security_options=noanonymous
	postconf -e relay_destination_concurrency_limit=20
	postconf -e header_size_limit=4096000

	echo "Configuring postfix TLS"
	postconf -e smtp_tls_loglevel=1
	postconf -e smtp_tls_security_level=encrypt
	postconf -e smtp_tls_note_starttls_offer=yes
	postconf -e smtpd_tls_security_level=may
	postconf -e smtpd_tls_loglevel=1
	postconf -e smtpd_tls_received_header=yes
	postconf -e smtpd_tls_auth_only=yes
	postconf -e smtpd_tls_cert_file="${SSL_CERT}"
	postconf -e smtpd_tls_key_file="${SSL_KEY}"
	postconf -e smtpd_tls_dh512_param_file=/etc/postfix/dh512.pem
}

configure_limits_and_throttling() {
	echo "Configuring postfix queue and limits"
	postconf -e smtpd_discard_ehlo_keywords="silent-discard, dsn"
	postconf -e soft_bounce=no
	postconf -e message_size_limit=52428800
	postconf -e mailbox_size_limit=0
	postconf -e recipient_delimiter=+
	postconf -e maximal_queue_lifetime=5d
	postconf -e bounce_queue_lifetime=5d
	postconf -e maximal_backoff_time=15m
	postconf -e minimal_backoff_time=5m
	postconf -e queue_run_delay=5m
	postconf -e smtpd_delay_reject=yes

	echo "Configuring postfix rate throttling"
	postconf -e smtpd_client_connection_rate_limit=3
	postconf -e anvil_rate_time_unit=60m
	postconf -e smtpd_error_sleep_time=10s
	postconf -e smtpd_soft_error_limit=4
	postconf -e smtpd_hard_error_limit=4
	postconf -e disable_vrfy_command=yes
}

configure_aliases_and_relay() {
	POSTMASTER_ALIAS=${POSTMASTER_ALIAS:-postmaster@${MYHOSTNAME:-localhost}}

	cat <<EOF>/etc/postfix/aliases
postmaster: ${POSTMASTER_ALIAS}
root: ${POSTMASTER_ALIAS}
EOF

	newaliases

	if [ -n "${RELAYHOST:-}" ]; then
		echo "> Forwarding all emails to ${RELAYHOST}"
		postconf -e "relayhost=${RELAYHOST}"
	fi

	if [ -n "${RELAY_USERNAME:-}" ] && [ -n "${RELAY_PASSWORD:-}" ]; then
		echo "> Using username and password for relay auth"
		postconf -e smtp_sasl_auth_enable=yes
		postconf -e smtp_sasl_password_maps=static:${RELAY_USERNAME}:${RELAY_PASSWORD}
		postconf -e smtp_sasl_security_options=noanonymous
		postconf -e relay_destination_concurrency_limit=20
		postconf -e header_size_limit=4096000
	fi
}

configure_optional_features() {
	if [ "${FILTER_MIME:-false}" = "true" ]; then
		postconf -e mime_header_checks=regexp:/etc/postfix/mime_header_checks
	fi
}

finalize_permissions() {
	echo "Fixing postfix permissions"
	postfix set-permissions create-missing
}

validate_postfix_config() {
	echo "Validating postfix configuration"
	postfix check
}

echo "Running init-postconf"
require_env MYHOSTNAME
require_env MYNETWORKS
require_env DOVECOT_HOST
require_env DOVECOT_LMTP
require_env DOVECOT_SASL
require_env SSL_CERT
require_env SSL_KEY
require_env PROXY_MAILNAME

configure_identity_and_network
configure_submission_service
configure_smtps_service
configure_maps_and_restrictions
configure_logging_milter_sasl_tls
configure_limits_and_throttling
configure_aliases_and_relay
configure_optional_features
#finalize_permissions
validate_postfix_config

echo "Completed configuration"
exit 0