#!/command/with-contenv bash

/usr/local/bin/dockerize \
  -template /etc/postfix/template/mysql-virtual-alias-maps.cf.templ:/etc/postfix/mysql-virtual-alias-maps.cf \
  -template /etc/postfix/template/mysql-virtual-mailbox-domains.cf.templ:/etc/postfix/mysql-virtual-mailbox-domains.cf \
  -template /etc/postfix/template/mysql-virtual-mailbox-maps.cf.templ:/etc/postfix/mysql-virtual-mailbox-maps.cf \
  -template /etc/postfix/template/mysql-virtual-mailbox-senders.cf.templ:/etc/postfix/mysql-virtual-mailbox-senders.cf \
  -template /etc/postfix/template/mysql-recipient-access.cf.templ:/etc/postfix/mysql-recipient-access.cf